# docker build -t cross-compile --file Dockerfile-nano .
# docker run -it --rm -v $(pwd):/out cross-compile

FROM debian:13
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /build

RUN dpkg --add-architecture armhf && \
    apt-get update && \
    apt install -y --no-install-recommends \
    wget ca-certificates file \
    build-essential \
    crossbuild-essential-armhf \
    libc6-dev:armhf libc6-dev-armhf-cross \
    libncurses-dev:armhf \
    texinfo

RUN wget https://www.nano-editor.org/dist/v8/nano-8.7.tar.xz && \
    tar xJf nano-8.7.tar.xz

ENV TARGET=arm-linux-gnueabihf
ENV CC="$TARGET-gcc"
ENV CXX="$TARGET-g++"
ENV AR="$TARGET-ar"
ENV LD="$TARGET-ld"
ENV AS="$TARGET-as"
ENV RANLIB="$TARGET-ranlib"
ENV STRIP="$TARGET-strip"

WORKDIR /build/nano-8.7

RUN ./configure --host=$TARGET --enable-utf8

RUN make -j"$(nproc)" CFLAGS="-O2 -Wall -static" LIBS="-lncursesw -ltinfo"

RUN file src/nano | grep -q 'statically linked'

CMD ["/bin/bash"]
