# docker build -t cross-compile --file Dockerfile-bftpd .
# docker run -it --rm -v $(pwd):/out cross-compile

FROM debian:13
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /build

RUN dpkg --add-architecture armhf && \
    apt update && \
    apt install -y --no-install-recommends \
    wget ca-certificates file \
    build-essential \
    crossbuild-essential-armhf \
    libc6-dev:armhf libc6-dev-armhf-cross

RUN wget https://downloads.sourceforge.net/project/bftpd/bftpd/bftpd-6.3/bftpd-6.3.tar.gz; && \
    tar xf bftpd-6.3.tar.gz

ENV TARGET=arm-linux-gnueabihf
ENV CC="$TARGET-gcc"
ENV CXX="$TARGET-g++"
ENV AR="$TARGET-ar"
ENV LD="$TARGET-ld"
ENV AS="$TARGET-as"
ENV RANLIB="$TARGET-ranlib"
ENV STRIP="$TARGET-strip"

WORKDIR /build/bftpd

RUN CC="arm-linux-gnueabihf-gcc -static" make

RUN file bftpd | grep -q 'statically linked'

CMD ["/bin/bash"]
