# docker build -t cross-compile --file Dockerfile-dropbear .
# docker run -it --rm -v $(pwd)/out:/out cross-compile

FROM debian:13
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /build

RUN dpkg --add-architecture armhf && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
    wget ca-certificates file \
    build-essential \
    crossbuild-essential-armhf \
    libc6-dev:armhf libc6-dev-armhf-cross

RUN wget https://matt.ucc.asn.au/dropbear/releases/dropbear-2025.88.tar.bz2 && \
    tar xjf dropbear-2025.88.tar.bz2

ENV TARGET=arm-linux-gnueabihf
ENV CC="$TARGET-gcc"
ENV CXX="$TARGET-g++"
ENV AR="$TARGET-ar"
ENV LD="$TARGET-ld"
ENV AS="$TARGET-as"
ENV RANLIB="$TARGET-ranlib"
ENV STRIP="$TARGET-strip"

WORKDIR /build/dropbear-2025.88

RUN cat << 'EOF' > localoptions.h
#define DROPBEAR_PATH_SSH_PROGRAM "/config/dbclient"
#define SFTPSERVER_PATH "/config/sftp-server"
#define DEFAULT_PATH "/bin:/sbin:/usr/bin:/usr/sbin:/config"
#define DEFAULT_ROOT_PATH "/usr/sbin:/usr/bin:/sbin:/bin:/config"
EOF

RUN ./configure --host=$TARGET CFLAGS="-Os" LDFLAGS="-static" --disable-zlib --disable-pam --disable-lastlog --disable-utmp --disable-wtmp --enable-static

RUN make -j"$(nproc)" PROGRAMS="dropbear dbclient dropbearkey scp" MULTI=1

RUN file dropbearmulti | grep -q 'statically linked'

CMD ["/bin/bash"]
